# Generated by Django 4.2.5 on 2023-09-12 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0003_person1_delete_shoppingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
