# Generated by Django 4.2.5 on 2023-09-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0004_person2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='category',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
