# Generated by Django 4.2.5 on 2023-09-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0006_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='color',
            field=models.CharField(default='#f5f5f5', max_length=10),
            preserve_default=False,
        ),
    ]
