# Generated by Django 4.2.5 on 2023-09-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0009_person4'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person1',
            table='mylist_person1',
        ),
        migrations.AlterModelTable(
            name='person2',
            table='mylist_person2',
        ),
        migrations.AlterModelTable(
            name='person3',
            table='mylist_person3',
        ),
        migrations.AlterModelTable(
            name='person4',
            table='mylist_person4',
        ),
    ]
