# Generated by Django 4.2.5 on 2023-09-21 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0010_alter_person1_table_alter_person2_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mylist_person5',
            },
        ),
    ]
