# Generated by Django 4.2.5 on 2023-09-21 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0011_person5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mylist_person10',
            },
        ),
        migrations.CreateModel(
            name='Person6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mylist_person6',
            },
        ),
        migrations.CreateModel(
            name='Person7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mylist_person7',
            },
        ),
        migrations.CreateModel(
            name='Person8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mylist_person8',
            },
        ),
        migrations.CreateModel(
            name='Person9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mylist_person9',
            },
        ),
    ]
