# Generated by Django 4.2.5 on 2023-09-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0012_person10_person6_person7_person8_person9'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
