# Generated by Django 4.2.5 on 2023-10-08 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0013_members_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('nr', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('cashflow', models.FloatField(default=0)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_save', models.IntegerField(default=0)),
                ('sum_save', models.FloatField(default=0)),
            ],
        ),
    ]
