# Generated by Django 4.2.5 on 2023-10-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0014_konto_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(choices=[('0', 'Johannes'), ('1', 'Sarita'), ('2', 'Osi')], max_length=1),
        ),
    ]
