# Generated by Django 4.2.5 on 2023-10-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0015_alter_pricelist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
