# Generated by Django 4.2.5 on 2023-10-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0016_alter_pricelist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konto',
            name='name',
            field=models.CharField(choices=[('0', 'Johannes'), ('1', 'Sarita'), ('2', 'Osi')], max_length=1),
        ),
    ]
