# Generated by Django 4.2.5 on 2023-10-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0018_alter_konto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konto',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='konto',
            name='nr',
            field=models.IntegerField(choices=[(0, '-'), (1, 'Huber/Hoffmann'), (2, 'Teßmann'), (3, 'Andrea Wenninger / Fam. Fiedler'), (4, 'Sonja Gartner'), (5, 'Hildegund & Osi'), (6, 'Sarita Schwerla')], default=0),
        ),
    ]
