# Generated by Django 4.2.5 on 2023-10-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0019_alter_konto_name_alter_konto_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konto',
            name='name',
        ),
    ]
