# Generated by Django 4.2.5 on 2023-10-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0020_remove_konto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='comment2',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='konto',
            name='comment',
            field=models.CharField(choices=[(0, '-'), (1, 'Huber/Hoffmann'), (2, 'Teßmann'), (3, 'Andrea Wenninger / Fam. Fiedler'), (4, 'Sonja Gartner'), (5, 'Hildegund & Osi'), (6, 'Sarita Schwerla')], max_length=200),
        ),
    ]
