# Generated by Django 4.2.5 on 2023-10-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0021_konto_comment2_alter_konto_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konto',
            name='comment',
            field=models.CharField(choices=[(0, '-'), (1, 'Einzahlung'), (2, 'Miete'), (3, 'Koop-Einkauf')], max_length=200),
        ),
    ]
