# Generated by Django 4.2.5 on 2023-10-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0022_alter_konto_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konto',
            name='comment',
            field=models.CharField(choices=[('-', '-'), ('Einzahlung', 'Einzahlung'), (2, 'Miete'), (3, 'Koop-Einkauf')], max_length=200),
        ),
    ]
