# Generated by Django 4.2.5 on 2023-11-01 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0025_alter_konto_comment_alter_konto_comment2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mylist_person11',
            },
        ),
        migrations.CreateModel(
            name='Person12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mylist_person12',
            },
        ),
        migrations.CreateModel(
            name='Person13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mylist_person13',
            },
        ),
        migrations.CreateModel(
            name='Person14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mylist_person14',
            },
        ),
        migrations.CreateModel(
            name='Person15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mylist_person15',
            },
        ),
    ]
