# Generated by Django 5.1 on 2024-09-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0027_alter_konto_created_at_alter_person1_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person1',
            options={'verbose_name': '[1] ...', 'verbose_name_plural': '[1] ...'},
        ),
        migrations.AlterModelOptions(
            name='person10',
            options={'verbose_name': '[10] ...', 'verbose_name_plural': '[10] ...'},
        ),
        migrations.AlterModelOptions(
            name='person11',
            options={'verbose_name': '[11] ...', 'verbose_name_plural': '[11] ...'},
        ),
        migrations.AlterModelOptions(
            name='person12',
            options={'verbose_name': '[12] ...', 'verbose_name_plural': '[12] ...'},
        ),
        migrations.AlterModelOptions(
            name='person13',
            options={'verbose_name': '[13] ...', 'verbose_name_plural': '[13] ...'},
        ),
        migrations.AlterModelOptions(
            name='person14',
            options={'verbose_name': '[14] ...', 'verbose_name_plural': '[14] ...'},
        ),
        migrations.AlterModelOptions(
            name='person15',
            options={'verbose_name': '[15] ...', 'verbose_name_plural': '[15] ...'},
        ),
        migrations.AlterModelOptions(
            name='person2',
            options={'verbose_name': '[2] ...', 'verbose_name_plural': '[2] ...'},
        ),
        migrations.AlterModelOptions(
            name='person3',
            options={'verbose_name': '[3] ...', 'verbose_name_plural': '[3] ...'},
        ),
        migrations.AlterModelOptions(
            name='person4',
            options={'verbose_name': '[4] ...', 'verbose_name_plural': '[4] ...'},
        ),
        migrations.AlterModelOptions(
            name='person5',
            options={'verbose_name': '[5] ...', 'verbose_name_plural': '[5] ...'},
        ),
        migrations.AlterModelOptions(
            name='person6',
            options={'verbose_name': '[6] ...', 'verbose_name_plural': '[6] ...'},
        ),
        migrations.AlterModelOptions(
            name='person7',
            options={'verbose_name': '[7] ...', 'verbose_name_plural': '[7] ...'},
        ),
        migrations.AlterModelOptions(
            name='person8',
            options={'verbose_name': '[8] ...', 'verbose_name_plural': '[8] ...'},
        ),
        migrations.AlterModelOptions(
            name='person9',
            options={'verbose_name': '[9] ...', 'verbose_name_plural': '[9] ...'},
        ),
        migrations.AlterField(
            model_name='konto',
            name='comment',
            field=models.CharField(choices=[('Einzahlung', 'Einzahlung'), ('Miete', 'Miete'), ('Koop-Einkauf', 'Koop-Einkauf'), ('Sonstiges', 'Sonstiges')], max_length=200),
        ),
        migrations.AlterField(
            model_name='konto',
            name='nr',
            field=models.IntegerField(choices=[(0, '-'), (1, '[1] Huber/Hoffmann'), (2, '[2] Teßmann'), (3, '[3] Wenninger/Fiedler'), (4, '[4] Sonja Gartner'), (5, '[5] Hildegund & Osi'), (6, '[6] Sarita Schwerla'), (7, '[7] Laux'), (8, '[8] Klaus Plessner'), (9, '[9] -'), (10, '[10] Susanne Zehetmeier'), (11, '[11] Nora Siebels'), (12, '[12] Schürkämper'), (13, '[13] Gabi Mitschka'), (14, '[14] Fritz Spörl')], default=0),
        ),
    ]
