# Generated by Django 5.1 on 2024-09-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0028_alter_person1_options_alter_person10_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person1',
            options={'verbose_name': '[1] Teßmann', 'verbose_name_plural': '[1] Teßmann'},
        ),
        migrations.AlterModelOptions(
            name='person10',
            options={'verbose_name': '[10] Gabi Mitschka', 'verbose_name_plural': '[10] Gabi Mitschka'},
        ),
        migrations.AlterModelOptions(
            name='person11',
            options={'verbose_name': '[11] Fritz Spörl', 'verbose_name_plural': '[11] Fritz Spörl'},
        ),
        migrations.AlterModelOptions(
            name='person12',
            options={'verbose_name': '[12] RESERVE1', 'verbose_name_plural': '[12] RESERVE1'},
        ),
        migrations.AlterModelOptions(
            name='person13',
            options={'verbose_name': '[13] RESERVE2', 'verbose_name_plural': '[13] RESERVE2'},
        ),
        migrations.AlterModelOptions(
            name='person14',
            options={'verbose_name': '[14] RESERVE3', 'verbose_name_plural': '[14] RESERVE3'},
        ),
        migrations.AlterModelOptions(
            name='person15',
            options={'verbose_name': '[15] RESERVE4', 'verbose_name_plural': '[15] RESERVE4'},
        ),
        migrations.AlterModelOptions(
            name='person2',
            options={'verbose_name': '[2] Wenninger/Fiedler', 'verbose_name_plural': '[2] Wenninger/Fiedler'},
        ),
        migrations.AlterModelOptions(
            name='person3',
            options={'verbose_name': '[3] Hildegund & Osi', 'verbose_name_plural': '[3] Hildegund & Osi'},
        ),
        migrations.AlterModelOptions(
            name='person4',
            options={'verbose_name': '[4] Sarita Schwerla', 'verbose_name_plural': '[4] Sarita Schwerla'},
        ),
        migrations.AlterModelOptions(
            name='person5',
            options={'verbose_name': '[5] Laux', 'verbose_name_plural': '[5] Laux'},
        ),
        migrations.AlterModelOptions(
            name='person6',
            options={'verbose_name': '[6] Klaus Plessner', 'verbose_name_plural': '[6] Klaus Plessner'},
        ),
        migrations.AlterModelOptions(
            name='person7',
            options={'verbose_name': '[7] Susanne Zehetmeier', 'verbose_name_plural': '[7] Susanne Zehetmeier'},
        ),
        migrations.AlterModelOptions(
            name='person8',
            options={'verbose_name': '[8] Nora Siebels', 'verbose_name_plural': '[8] Nora Siebels'},
        ),
        migrations.AlterModelOptions(
            name='person9',
            options={'verbose_name': '[9] Schürkämper', 'verbose_name_plural': '[9] Schürkämper'},
        ),
    ]
