# Generated by Django 5.1.1 on 2024-09-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0029_alter_person1_options_alter_person10_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person1',
            options={'verbose_name': '[1] Huber/Hoffmann', 'verbose_name_plural': '[1] Huber/Hoffmann'},
        ),
        migrations.AlterModelOptions(
            name='person10',
            options={'verbose_name': '[10] Nora Siebels', 'verbose_name_plural': '[10] Nora Siebels'},
        ),
        migrations.AlterModelOptions(
            name='person11',
            options={'verbose_name': '[11] Schürkämper', 'verbose_name_plural': '[11] Schürkämper'},
        ),
        migrations.AlterModelOptions(
            name='person12',
            options={'verbose_name': '[12] Gabi Mitschka', 'verbose_name_plural': '[12] Gabi Mitschka'},
        ),
        migrations.AlterModelOptions(
            name='person13',
            options={'verbose_name': '[13] Fritz Spörl', 'verbose_name_plural': '[13] Fritz Spörl'},
        ),
        migrations.AlterModelOptions(
            name='person14',
            options={'verbose_name': '[14] -', 'verbose_name_plural': '[14] -'},
        ),
        migrations.AlterModelOptions(
            name='person15',
            options={'verbose_name': '[15] -', 'verbose_name_plural': '[15] -'},
        ),
        migrations.AlterModelOptions(
            name='person2',
            options={'verbose_name': '[2] Teßmann', 'verbose_name_plural': '[2] Teßmann'},
        ),
        migrations.AlterModelOptions(
            name='person3',
            options={'verbose_name': '[3] Wenninger/Fiedler', 'verbose_name_plural': '[3] Wenninger/Fiedler'},
        ),
        migrations.AlterModelOptions(
            name='person4',
            options={'verbose_name': '[4] Hildegund & Osi', 'verbose_name_plural': '[4] Hildegund & Osi'},
        ),
        migrations.AlterModelOptions(
            name='person5',
            options={'verbose_name': '[5] Sarita Schwerla', 'verbose_name_plural': '[5] Sarita Schwerla'},
        ),
        migrations.AlterModelOptions(
            name='person6',
            options={'verbose_name': '[6] Laux', 'verbose_name_plural': '[6] Laux'},
        ),
        migrations.AlterModelOptions(
            name='person7',
            options={'verbose_name': '[7] Klaus Plessner', 'verbose_name_plural': '[7] Klaus Plessner'},
        ),
        migrations.AlterModelOptions(
            name='person8',
            options={'verbose_name': '[8] Susanne Zehetmeier', 'verbose_name_plural': '[8] Susanne Zehetmeier'},
        ),
        migrations.AlterModelOptions(
            name='person9',
            options={'verbose_name': '[9] -', 'verbose_name_plural': '[9] -'},
        ),
    ]
