# Generated by Django 5.1 on 2024-10-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0030_alter_person1_options_alter_person10_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warenliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikelnummer', models.IntegerField(default=0)),
                ('artikelname', models.CharField(max_length=200)),
                ('sortiment', models.CharField(max_length=200)),
                ('artikelname_neu', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='person1',
            options={'verbose_name': '[1] Huber/Hoffmann - 2 Personen', 'verbose_name_plural': '[1] Huber/Hoffmann - 2 Personen'},
        ),
        migrations.AlterModelOptions(
            name='person10',
            options={'verbose_name': '[10] Susanne Zehetmeier - 1 Person', 'verbose_name_plural': '[10] Susanne Zehetmeier - 1 Person'},
        ),
        migrations.AlterModelOptions(
            name='person11',
            options={'verbose_name': '[11] Nora Siebels - 2 Personen', 'verbose_name_plural': '[11] Nora Siebels - 2 Personen'},
        ),
        migrations.AlterModelOptions(
            name='person12',
            options={'verbose_name': '[12] Schürkämper - 2 Personen', 'verbose_name_plural': '[12] Schürkämper - 2 Personen'},
        ),
        migrations.AlterModelOptions(
            name='person13',
            options={'verbose_name': '[13] Gabi Mitschka - 1 Person', 'verbose_name_plural': '[13] Gabi Mitschka - 1 Person'},
        ),
        migrations.AlterModelOptions(
            name='person14',
            options={'verbose_name': '[14] Fritz Spörl - 1 Person', 'verbose_name_plural': '[14] Fritz Spörl - 1 Person'},
        ),
        migrations.AlterModelOptions(
            name='person2',
            options={'verbose_name': '[2] Teßmann - 2 Personen', 'verbose_name_plural': '[2] Teßmann - 2 Personen'},
        ),
        migrations.AlterModelOptions(
            name='person3',
            options={'verbose_name': '[3] Andrea Wenninger / Fam. Fiedler - 2 Personen', 'verbose_name_plural': '[3] Andrea Wenninger / Fam. Fiedler - 2 Personen'},
        ),
        migrations.AlterModelOptions(
            name='person4',
            options={'verbose_name': '[4] Sonja Gartner - 1 Person', 'verbose_name_plural': '[4] Sonja Gartner - 1 Person'},
        ),
        migrations.AlterModelOptions(
            name='person5',
            options={'verbose_name': '[5] Hildegund & Osi - 2 Personen', 'verbose_name_plural': '[5] Hildegund & Osi - 2 Personen'},
        ),
        migrations.AlterModelOptions(
            name='person6',
            options={'verbose_name': '[6] Sarita Schwerla - 2 Personen', 'verbose_name_plural': '[6] Sarita Schwerla - 2 Personen'},
        ),
        migrations.AlterModelOptions(
            name='person7',
            options={'verbose_name': '[7] Christine und Gerhard Laux - 2 Personen', 'verbose_name_plural': '[7] Christine und Gerhard Laux - 2 Personen'},
        ),
        migrations.AlterModelOptions(
            name='person8',
            options={'verbose_name': '[8] Klaus - 1 Person', 'verbose_name_plural': '[8] Klaus - 1 Person'},
        ),
    ]
