# Generated by Django 5.1 on 2024-10-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0031_warenliste_alter_person1_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
