# Generated by Django 5.1 on 2024-10-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0033_alter_person1_options_alter_person10_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='name_nr',
            field=models.IntegerField(default=0),
        ),
    ]
