# Generated by Django 5.1 on 2024-10-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0034_members_name_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='article_number',
            field=models.IntegerField(default=0),
        ),
    ]
