# Generated by Django 5.1 on 2024-10-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0035_pricelist_article_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='type',
            field=models.CharField(choices=[('Stk', 'Stück'), ('kg', 'Kilogramm')], max_length=5),
        ),
    ]
