# Generated by Django 5.1 on 2024-10-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0036_alter_pricelist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='category',
            field=models.CharField(choices=[('Obst', 'Obst'), ('Gemüse', 'Gemüse'), ('Frischwaren', 'Frischwaren'), ('Fleisch', 'Fleisch'), ('Getränke', 'Getränke'), ('Tiefkühl', 'Tiefkühl')], default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='type',
            field=models.CharField(choices=[('Stk', 'Stk'), ('kg', 'kg')], max_length=5),
        ),
    ]
