# Generated by Django 5.1 on 2024-10-11 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0037_alter_pricelist_category_alter_pricelist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='type',
            field=models.CharField(choices=[('Stk', 'Stk'), ('kg', 'kg'), ('Pfand', 'Pfand')], max_length=5),
        ),
    ]
