# Generated by Django 5.1 on 2024-10-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0038_pricelist_created_at_alter_pricelist_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='delivery_date',
            field=models.CharField(default='01.01.1999', max_length=10),
        ),
    ]
