# Generated by Django 5.1 on 2024-10-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0039_pricelist_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='delivery_date',
            field=models.DateTimeField(default='01.01.1999'),
        ),
    ]
