# Generated by Django 5.1 on 2024-10-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0040_alter_pricelist_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='delivery_date',
            field=models.DateField(default='10.10.1999'),
        ),
    ]
