# Generated by Django 4.2.16 on 2024-10-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0041_alter_pricelist_delivery_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person1',
            options={'verbose_name': '[1] 2 - Huber/Hoffmann - 2 Personen - #4552b5 - 0.0', 'verbose_name_plural': '[1] 2 - Huber/Hoffmann - 2 Personen - #4552b5 - 0.0'},
        ),
        migrations.AlterModelOptions(
            name='person10',
            options={'verbose_name': '[10] 11 - Susanne Zehetmeier - 1 Person - #FFFFFF - 0.0', 'verbose_name_plural': '[10] 11 - Susanne Zehetmeier - 1 Person - #FFFFFF - 0.0'},
        ),
        migrations.AlterModelOptions(
            name='person11',
            options={'verbose_name': '[11] 12 - Nora Siebels - 2 Personen - #0F0ABB - 23.75', 'verbose_name_plural': '[11] 12 - Nora Siebels - 2 Personen - #0F0ABB - 23.75'},
        ),
        migrations.AlterModelOptions(
            name='person12',
            options={'verbose_name': '[12] 13 - Schürkämper - 2 Personen - #2f666e - 49.09', 'verbose_name_plural': '[12] 13 - Schürkämper - 2 Personen - #2f666e - 49.09'},
        ),
        migrations.AlterModelOptions(
            name='person13',
            options={'verbose_name': '[13] 14 - Gabi Mitschka - 1 Person - #22ffff - 70.17', 'verbose_name_plural': '[13] 14 - Gabi Mitschka - 1 Person - #22ffff - 70.17'},
        ),
        migrations.AlterModelOptions(
            name='person14',
            options={'verbose_name': '[14] 15 - Fritz Spörl - 1 Person - #ffff33 - 0.0', 'verbose_name_plural': '[14] 15 - Fritz Spörl - 1 Person - #ffff33 - 0.0'},
        ),
        migrations.AlterModelOptions(
            name='person15',
            options={'verbose_name': '[15] 25 - - - #ffffff - 0.0', 'verbose_name_plural': '[15] 25 - - - #ffffff - 0.0'},
        ),
        migrations.AlterModelOptions(
            name='person2',
            options={'verbose_name': '[2] 3 - Teßmann - 2 Personen - #db34eb - 3.75', 'verbose_name_plural': '[2] 3 - Teßmann - 2 Personen - #db34eb - 3.75'},
        ),
        migrations.AlterModelOptions(
            name='person3',
            options={'verbose_name': '[3] 4 - Andrea Wenninger / Fam. Fiedler - 2 Personen - #2fb30e - 0.0', 'verbose_name_plural': '[3] 4 - Andrea Wenninger / Fam. Fiedler - 2 Personen - #2fb30e - 0.0'},
        ),
        migrations.AlterModelOptions(
            name='person4',
            options={'verbose_name': '[4] 5 - Sonja Gartner - 1 Person - #507538 - 0.0', 'verbose_name_plural': '[4] 5 - Sonja Gartner - 1 Person - #507538 - 0.0'},
        ),
        migrations.AlterModelOptions(
            name='person5',
            options={'verbose_name': '[5] 6 - Hildegund & Osi - 2 Personen - #429ef5 - 0.0', 'verbose_name_plural': '[5] 6 - Hildegund & Osi - 2 Personen - #429ef5 - 0.0'},
        ),
        migrations.AlterModelOptions(
            name='person6',
            options={'verbose_name': '[6] 7 - Sarita Schwerla - 2 Personen - #4103fc - 0.0', 'verbose_name_plural': '[6] 7 - Sarita Schwerla - 2 Personen - #4103fc - 0.0'},
        ),
        migrations.AlterModelOptions(
            name='person7',
            options={'verbose_name': '[7] 8 - Christine und Gerhard Laux - 2 Personen - #fcdb03 - 0.0', 'verbose_name_plural': '[7] 8 - Christine und Gerhard Laux - 2 Personen - #fcdb03 - 0.0'},
        ),
        migrations.AlterModelOptions(
            name='person8',
            options={'verbose_name': '[8] 9 - Klaus - 1 Person - #888888 - 34.6', 'verbose_name_plural': '[8] 9 - Klaus - 1 Person - #888888 - 34.6'},
        ),
        migrations.AlterModelOptions(
            name='person9',
            options={'verbose_name': '[9] 10 - - - #FFFFFF - 0.0', 'verbose_name_plural': '[9] 10 - - - #FFFFFF - 0.0'},
        ),
    ]
