# Generated by Django 4.2.16 on 2024-10-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0042_alter_person1_options_alter_person10_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person1',
            options={'verbose_name': '[1] Huber/Hoffmann', 'verbose_name_plural': '[1] Huber/Hoffmann'},
        ),
        migrations.AlterModelOptions(
            name='person10',
            options={'verbose_name': '[10] Susanne Zehetmeier', 'verbose_name_plural': '[10] Susanne Zehetmeier'},
        ),
        migrations.AlterModelOptions(
            name='person11',
            options={'verbose_name': '[11] Nora Siebels', 'verbose_name_plural': '[11] Nora Siebels'},
        ),
        migrations.AlterModelOptions(
            name='person12',
            options={'verbose_name': '[12] Schürkämper', 'verbose_name_plural': '[12] Schürkämper'},
        ),
        migrations.AlterModelOptions(
            name='person13',
            options={'verbose_name': '[13] Gabi Mitschka', 'verbose_name_plural': '[13] Gabi Mitschka'},
        ),
        migrations.AlterModelOptions(
            name='person14',
            options={'verbose_name': '[14] Fritz Spörl', 'verbose_name_plural': '[14] Fritz Spörl'},
        ),
        migrations.AlterModelOptions(
            name='person15',
            options={'verbose_name': '[15] -', 'verbose_name_plural': '[15] -'},
        ),
        migrations.AlterModelOptions(
            name='person2',
            options={'verbose_name': '[2] Teßmann', 'verbose_name_plural': '[2] Teßmann'},
        ),
        migrations.AlterModelOptions(
            name='person3',
            options={'verbose_name': '[3] Wenninger/Fiedler', 'verbose_name_plural': '[3] Wenninger/Fiedler'},
        ),
        migrations.AlterModelOptions(
            name='person4',
            options={'verbose_name': '[4] Sonja Gartner', 'verbose_name_plural': '[4] Sonja Gartner'},
        ),
        migrations.AlterModelOptions(
            name='person5',
            options={'verbose_name': '[5] Hildegund & Osi', 'verbose_name_plural': '[5] Hildegund & Osi'},
        ),
        migrations.AlterModelOptions(
            name='person6',
            options={'verbose_name': '[6] Sarita Schwerla', 'verbose_name_plural': '[6] Sarita Schwerla'},
        ),
        migrations.AlterModelOptions(
            name='person7',
            options={'verbose_name': '[7] Laux', 'verbose_name_plural': '[7] Laux'},
        ),
        migrations.AlterModelOptions(
            name='person8',
            options={'verbose_name': '[8] Klaus Plessner', 'verbose_name_plural': '[8] Klaus Plessner'},
        ),
        migrations.AlterModelOptions(
            name='person9',
            options={'verbose_name': '[9] -', 'verbose_name_plural': '[9] -'},
        ),
    ]
