# Generated by Django 5.2.2 on 2025-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0043_alter_person1_options_alter_person10_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person9',
            options={'verbose_name': '[9] Koller', 'verbose_name_plural': '[9] Koller'},
        ),
        migrations.AlterField(
            model_name='konto',
            name='nr',
            field=models.IntegerField(choices=[(0, '-'), (1, '[1] Huber/Hoffmann'), (2, '[2] Teßmann'), (3, '[3] Wenninger/Fiedler'), (4, '[4] Sonja Gartner'), (5, '[5] Hildegund & Osi'), (6, '[6] Sarita Schwerla'), (7, '[7] Laux'), (8, '[8] Klaus Plessner'), (9, '[9] Koller'), (10, '[10] Susanne Zehetmeier'), (11, '[11] Nora Siebels'), (12, '[12] Schürkämper'), (13, '[13] Gabi Mitschka'), (14, '[14] Fritz Spörl')], default=0),
        ),
    ]
