# Generated by Django 5.2.2 on 2025-06-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0044_alter_person9_options_alter_konto_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='persons',
            field=models.IntegerField(default=1),
        ),
    ]
