# Generated by Django 5.2.2 on 2025-06-08 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0045_members_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
