# Generated by Django 5.2.2 on 2025-06-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0046_konto_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='name_nr',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
