# Generated by Django 5.2.2 on 2025-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0047_alter_members_name_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='rent_save',
            field=models.FloatField(default=16),
        ),
    ]
