# Generated by Django 5.2.2 on 2025-06-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0048_save_rent_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konto',
            name='nr',
            field=models.IntegerField(choices=[(0, '-'), (1, 'Huber/Hoffmann'), (2, 'Teßmann'), (3, 'Wenninger/Fiedler'), (4, 'Sonja Gartner'), (5, 'Hildegund & Osi'), (6, 'Sarita Schwerla'), (7, 'Laux'), (8, 'Klaus Plessner'), (9, 'Koller'), (10, 'Susanne Zehetmeier'), (11, 'Nora Siebels'), (12, 'Schürkämper'), (13, 'Gabi Mitschka'), (14, 'Fritz Spörl'), (15, '-')], default=0),
        ),
    ]
