# Generated by Django 5.2.2 on 2025-06-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0049_alter_konto_nr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person1',
            options={'verbose_name': '[1] 2 - Huber/Hoffmann-2 - #4552b5 - 117.05', 'verbose_name_plural': '[1] 2 - Huber/Hoffmann-2 - #4552b5 - 117.05'},
        ),
        migrations.AlterModelOptions(
            name='person10',
            options={'verbose_name': '[10] 11 - Susanne Zehetmeier-1 - #FFFFFF - 0.0', 'verbose_name_plural': '[10] 11 - Susanne Zehetmeier-1 - #FFFFFF - 0.0'},
        ),
        migrations.AlterModelOptions(
            name='person11',
            options={'verbose_name': '[11] 12 - FREI_11-0 - #0F0ABB - 0.0', 'verbose_name_plural': '[11] 12 - FREI_11-0 - #0F0ABB - 0.0'},
        ),
        migrations.AlterModelOptions(
            name='person12',
            options={'verbose_name': '[12] 13 - Schürkämper-2 - #2f666e - 64.83', 'verbose_name_plural': '[12] 13 - Schürkämper-2 - #2f666e - 64.83'},
        ),
        migrations.AlterModelOptions(
            name='person13',
            options={'verbose_name': '[13] 14 - Gabi Mitschka-1 - #22ffff - 67.69', 'verbose_name_plural': '[13] 14 - Gabi Mitschka-1 - #22ffff - 67.69'},
        ),
        migrations.AlterModelOptions(
            name='person14',
            options={'verbose_name': '[14] 15 - Fritz Spörl-1 - #ffff33 - 78.81', 'verbose_name_plural': '[14] 15 - Fritz Spörl-1 - #ffff33 - 78.81'},
        ),
        migrations.AlterModelOptions(
            name='person15',
            options={'verbose_name': '[15] 25 - FREI_15-0 - #ffffff - 0.0', 'verbose_name_plural': '[15] 25 - FREI_15-0 - #ffffff - 0.0'},
        ),
        migrations.AlterModelOptions(
            name='person2',
            options={'verbose_name': '[2] 3 - Teßmann-2 - #db34eb - 79.71', 'verbose_name_plural': '[2] 3 - Teßmann-2 - #db34eb - 79.71'},
        ),
        migrations.AlterModelOptions(
            name='person3',
            options={'verbose_name': '[3] 4 - Andrea Wenninger / Fiedler-2 - #2fb30e - 4.35', 'verbose_name_plural': '[3] 4 - Andrea Wenninger / Fiedler-2 - #2fb30e - 4.35'},
        ),
        migrations.AlterModelOptions(
            name='person4',
            options={'verbose_name': '[4] 5 - Sonja Gartner-1 - #507538 - 62.26', 'verbose_name_plural': '[4] 5 - Sonja Gartner-1 - #507538 - 62.26'},
        ),
        migrations.AlterModelOptions(
            name='person5',
            options={'verbose_name': '[5] 6 - Hildegund & Osi-2 - #429ef5 - 354.61', 'verbose_name_plural': '[5] 6 - Hildegund & Osi-2 - #429ef5 - 354.61'},
        ),
        migrations.AlterModelOptions(
            name='person6',
            options={'verbose_name': '[6] 7 - Sarita Schwerla-2 - #4103fc - 109.17', 'verbose_name_plural': '[6] 7 - Sarita Schwerla-2 - #4103fc - 109.17'},
        ),
        migrations.AlterModelOptions(
            name='person7',
            options={'verbose_name': '[7] 8 - Christine und Gerhard Laux-2 - #fcdb03 - 122.79', 'verbose_name_plural': '[7] 8 - Christine und Gerhard Laux-2 - #fcdb03 - 122.79'},
        ),
        migrations.AlterModelOptions(
            name='person8',
            options={'verbose_name': '[8] 9 - Klaus-1 - #888888 - 67.97', 'verbose_name_plural': '[8] 9 - Klaus-1 - #888888 - 67.97'},
        ),
        migrations.AlterModelOptions(
            name='person9',
            options={'verbose_name': '[9] 10 - Koller-2 - #008800 - 49.04', 'verbose_name_plural': '[9] 10 - Koller-2 - #008800 - 49.04'},
        ),
        migrations.AlterField(
            model_name='konto',
            name='nr',
            field=models.IntegerField(choices=[(0, '[0] -'), (1, '[1] Huber/Hoffmann'), (2, '[2] Teßmann'), (3, '[3] Wenninger/Fiedler'), (4, '[4] Sonja Gartner'), (5, '[5] Hildegund & Osi'), (6, '[6] Sarita Schwerla'), (7, '[7] Laux'), (8, '[8] Klaus Plessner'), (9, '[9] Koller'), (10, '[10] Susanne Zehetmeier'), (11, '[11] -'), (12, '[12] Schürkämper'), (13, '[13] Gabi Mitschka'), (14, '[14] Fritz Spörl'), (15, '[15] -')], default=0),
        ),
    ]
